//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3dpBurner {
	using System;
	
	
	/// <summary>
	///   A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	// This class was auto-generated by the StronglyTypedResourceBuilder
	// class via a tool like ResGen or Visual Studio.
	// To add or remove a member, edit your .ResX file then rerun ResGen
	// with the /str option, or rebuild your VS project.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Strings {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Strings() {
		}
		
		/// <summary>
		///   Returns the cached ResourceManager instance used by this class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_3dpBurner.Strings", typeof(Strings).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Overrides the current thread's CurrentUICulture property for all
		///   resource lookups using this strongly typed resource class.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Application exception.
		/// </summary>
		internal static string applicationException {
			get {
				return ResourceManager.GetString("applicationException", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Close
		///.
		/// </summary>
		internal static string buttonTextPortClose {
			get {
				return ResourceManager.GetString("buttonTextPortClose", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Open
		///.
		/// </summary>
		internal static string buttonTextPortOpen {
			get {
				return ResourceManager.GetString("buttonTextPortOpen", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to PWR.
		/// </summary>
		internal static string buttonTextPower {
			get {
				return ResourceManager.GetString("buttonTextPower", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to RPM.
		/// </summary>
		internal static string buttonTextSpeed {
			get {
				return ResourceManager.GetString("buttonTextSpeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error reading line from serial port.
		/// </summary>
		internal static string errorSerialRead {
			get {
				return ResourceManager.GetString("errorSerialRead", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Laser.
		/// </summary>
		internal static string groupBoxCaptionLaser {
			get {
				return ResourceManager.GetString("groupBoxCaptionLaser", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Spindle
		///.
		/// </summary>
		internal static string groupBoxCaptionSpindle {
			get {
				return ResourceManager.GetString("groupBoxCaptionSpindle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to {0}% ({1}/{2} lines).
		/// </summary>
		internal static string labelTextFileProgress {
			get {
				return ResourceManager.GetString("labelTextFileProgress", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to [Error]: {0}. .
		/// </summary>
		internal static string logError {
			get {
				return ResourceManager.GetString("logError", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Error opening file.
		/// </summary>
		internal static string logErrorFileOpen {
			get {
				return ResourceManager.GetString("logErrorFileOpen", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Retrieving GRBL status.
		/// </summary>
		internal static string logErrorGRBLStatus {
			get {
				return ResourceManager.GetString("logErrorGRBLStatus", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Sending line.
		/// </summary>
		internal static string logErrorLineSend {
			get {
				return ResourceManager.GetString("logErrorLineSend", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Closing port.
		/// </summary>
		internal static string logErrorPortClose {
			get {
				return ResourceManager.GetString("logErrorPortClose", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Opening port.
		/// </summary>
		internal static string logErrorPortOpen {
			get {
				return ResourceManager.GetString("logErrorPortOpen", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to No serial ports found.
		/// </summary>
		internal static string logErrorPortsNotFound {
			get {
				return ResourceManager.GetString("logErrorPortsNotFound", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Loading settings.
		/// </summary>
		internal static string logErrorSettingsLoad {
			get {
				return ResourceManager.GetString("logErrorSettingsLoad", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Saving settings.
		/// </summary>
		internal static string logErrorSettingsSave {
			get {
				return ResourceManager.GetString("logErrorSettingsSave", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to [File done @{0}]
		///.
		/// </summary>
		internal static string logFileDone {
			get {
				return ResourceManager.GetString("logFileDone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to [Sending file...]
		///.
		/// </summary>
		internal static string logFileSend {
			get {
				return ResourceManager.GetString("logFileSend", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Done.
		/// </summary>
		internal static string msbBoxCaptionFileDone {
			get {
				return ResourceManager.GetString("msbBoxCaptionFileDone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Restore Settings?.
		/// </summary>
		internal static string msbBoxMessageSettingsReset {
			get {
				return ResourceManager.GetString("msbBoxMessageSettingsReset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Restore Settings.
		/// </summary>
		internal static string msgBoxCaptionSettingsReset {
			get {
				return ResourceManager.GetString("msgBoxCaptionSettingsReset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Yeah!. Burning Done!
		///
		///Elapsed time: {0}.
		/// </summary>
		internal static string msgBoxMessageFileDone {
			get {
				return ResourceManager.GetString("msgBoxMessageFileDone", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Alarm.
		/// </summary>
		internal static string statusAlarm {
			get {
				return ResourceManager.GetString("statusAlarm", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Hold.
		/// </summary>
		internal static string statusHold {
			get {
				return ResourceManager.GetString("statusHold", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Home.
		/// </summary>
		internal static string statusHome {
			get {
				return ResourceManager.GetString("statusHome", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Idle.
		/// </summary>
		internal static string statusIdle {
			get {
				return ResourceManager.GetString("statusIdle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Queue.
		/// </summary>
		internal static string statusQueue {
			get {
				return ResourceManager.GetString("statusQueue", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Run.
		/// </summary>
		internal static string statusRun {
			get {
				return ResourceManager.GetString("statusRun", resourceCulture);
			}
		}
		
		/// <summary>
		///   Looks up a localized string similar to Thread exception.
		/// </summary>
		internal static string threadException {
			get {
				return ResourceManager.GetString("threadException", resourceCulture);
			}
		}
	}
}
